// <auto-generated />
using System;
using ExamTrainer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExamTrainer.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20220401071902_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.3");

            modelBuilder.Entity("ExamTrainer.Models.Anwser", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Questionid")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("isCorrect")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.HasIndex("Questionid");

                    b.ToTable("Anwsers");
                });

            modelBuilder.Entity("ExamTrainer.Models.Exam", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Exams");
                });

            modelBuilder.Entity("ExamTrainer.Models.Question", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Examid")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.HasIndex("Examid");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("ExamTrainer.Models.Anwser", b =>
                {
                    b.HasOne("ExamTrainer.Models.Question", null)
                        .WithMany("Anwsers")
                        .HasForeignKey("Questionid");
                });

            modelBuilder.Entity("ExamTrainer.Models.Question", b =>
                {
                    b.HasOne("ExamTrainer.Models.Exam", null)
                        .WithMany("Questions")
                        .HasForeignKey("Examid");
                });

            modelBuilder.Entity("ExamTrainer.Models.Exam", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("ExamTrainer.Models.Question", b =>
                {
                    b.Navigation("Anwsers");
                });
#pragma warning restore 612, 618
        }
    }
}
